
path_to_write:
  "/Users/orikobi/Library/CloudStorage/GoogleDrive-orikobi@mail.tau.ac.il/Shared drives/Halperin Lab/RESEARCH PROJECTS/RPE in soccer (ORI)/data/charts/"

basic_path: '/Users/orikobi/Library/CloudStorage/GoogleDrive-orikobi@mail.tau.ac.il/Shared drives/Halperin Lab/RESEARCH PROJECTS/RPE in soccer (ORI)/data'



cols_to_read:
  - 'Date'
  - 'Phase Type'
  - 'Phase Start Time'
  - 'Phase Duration (min)'
  - 'Player Name'
  - 'Top Speed (m/s)'
  - 'Work Rate (m/min)'
  - 'Distance Covered (m)'
  - 'SD Covered (m) [> 4.2(m/s)]'
  - 'Sprint Count (#)'
  - 'Speed Zone - Distance Covered (m) Zone 1 [0-1.5(m/s)]'
  - 'Speed Zone - Distance Covered (m) Zone 2 [1.5-2(m/s)]'
  - 'Speed Zone - Distance Covered (m) Zone 3 [2-3(m/s)]'
  - 'Speed Zone - Distance Covered (m) Zone 4 [3-4(m/s)]'
  - 'Speed Zone - Distance Covered (m) Zone 5 [4-5.5(m/s)]'
  - 'Speed Zone - Distance Covered (m) Zone 6 [5.5-7(m/s)]'
  - 'Speed Zone - Distance Covered (m) Zone 7 [> 7(m/s)]'
  - 'Intense Speed Changes Acc/Decl actions (#) [> 2.6(m/s^2)]'
  - 'Intense Speed Changes Acc/Decl actions per min (#/min)'
  - 'Horizontal Acc Zones (#) Zone 1 [0-0.4(m/s^2)]'
  - 'Horizontal Acc Zones (#) Zone 2 [0.4-0.9(m/s^2)]'
  - 'Horizontal Acc Zones (#) Zone 3 [0.9-1.5(m/s^2)]'
  - 'Horizontal Acc Zones (#) Zone 4 [1.5-2(m/s^2)]'
  - 'Horizontal Acc Zones (#) Zone 5 [2-2.6(m/s^2)]'
  - 'Horizontal Acc Zones (#) Zone 6 [> 2.6(m/s^2)]'



cols_mapping:
  'Distance Covered (m)': 'Distance'
  'Speed Zone - Distance Covered (m) Zone 1 [0-1.5(m/s)]': 'Zone 1'
  'Speed Zone - Distance Covered (m) Zone 2 [1.5-2(m/s)]': 'Zone 2'
  'Speed Zone - Distance Covered (m) Zone 3 [2-3(m/s)]': 'Zone 3'
  'Speed Zone - Distance Covered (m) Zone 4 [3-4(m/s)]': 'Zone 4'
  'Speed Zone - Distance Covered (m) Zone 5 [4-5.5(m/s)]': 'Zone 5'
  'Speed Zone - Distance Covered (m) Zone 6 [5.5-7(m/s)]': 'Zone 6'
  'Speed Zone - Distance Covered (m) Zone 7 [> 7(m/s)]':  'Zone 7'
  'Sprint Count (#)': 'sprint_count'
  'SD Covered (m) [> 4.2(m/s)]': 'SD Covered'
  'Intense Speed Changes Acc/Decl actions (#) [> 2.6(m/s^2)]': 'Intense Acc_Decl actions'
  'Top Speed (m/s)': 'Top Speed'
  'Horizontal Acc Zones (#) Zone 1 [0-0.4(m/s^2)]': 'Zone 1-accel'
  'Horizontal Acc Zones (#) Zone 2 [0.4-0.9(m/s^2)]': 'Zone 2-accel'
  'Horizontal Acc Zones (#) Zone 3 [0.9-1.5(m/s^2)]': 'Zone 3-accel'
  'Horizontal Acc Zones (#) Zone 4 [1.5-2(m/s^2)]': 'Zone 4-accel'
  'Horizontal Acc Zones (#) Zone 5 [2-2.6(m/s^2)]': 'Zone 5-accel'
  'Horizontal Acc Zones (#) Zone 6 [> 2.6(m/s^2)]': 'Zone 6-accel'
  'Work Rate (m/min)': 'Work Rate'
